#pragma once
#include "../common.h"
#include "../object_script.h"

#include "checkbox.h"
#include "clickable.h"
#include "draggable_root.h"
#include "moving_test.h"
#include "slider.h"
#include "texture_renderer.h"
#include "text_renderer.h"
#include "window_anchor.h"
#include "window_rect_anchor.h"
#include "timer.h"
#include "text_input.h"